import { supabase } from './supabase.js';
import { state } from './state.js';
import { $, msg, niceDate, nextTuesday } from './utils.js';
import { loadSession, loadLoginPlayers, bindAuth } from './auth.js';

let modules=null;let modulesPromise=null;
async function loadModules(){if(modules)return modules;if(!modulesPromise)modulesPromise=Promise.all([import('./poll.js'),import('./schedule.js'),import('./matches.js'),import('./payments.js'),import('./admin.js'),import('./notifications.js'),import('./cancellations.js'),import('./history.js'),import('./stats.js'),import('./admin-poll-test.js')]).then(([poll,schedule,matches,payments,admin,notifications,cancellations,history,stats,adminPollTest])=>({poll,schedule,matches,payments,admin,notifications,cancellations,history,stats,adminPollTest}));modules=await modulesPromise;return modules;}
const tabStyle=document.createElement('style');tabStyle.textContent='@media (min-width:761px){.tabs{gap:4px;overflow-x:auto;scrollbar-width:auto;overscroll-behavior-x:contain}.tab{padding:8px 9px;min-height:40px;font-size:12px;letter-spacing:-.01em}}';document.head.appendChild(tabStyle);
async function refreshCurrentPlayer(){const existing=state.currentPlayer;const {data:{session}}=await supabase.auth.getSession();if(!session?.user?.id)return existing||null;const q=await supabase.from('players').select('id,name,active,is_admin,is_stammspieler,paypal_email,auth_user_id,login_email,password_initialized').eq('auth_user_id',session.user.id).maybeSingle();if(q.error){console.warn('Aktueller Spieler konnte nicht erneut geladen werden; vorhandene Session-Daten werden verwendet.',q.error);if(existing?.is_admin===true&&$('who'))$('who').textContent=existing.name+' 👑';return existing||null;}if(!q.data||q.data.active===false)return null;state.currentPlayer=q.data;if($('who'))$('who').textContent=q.data.name+(q.data.is_admin?' 👑':'');return q.data;}
function localDateString(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`;}
async function currentMatchDayDate(){const today=localDateString();const future=await supabase.from('match_days').select('match_date').gt('match_date',today).eq('poll_open',true).eq('poll_closed',false).order('match_date').limit(1).maybeSingle();if(future.data?.match_date)return future.data.match_date;if(new Date().getDay()===2)return today;const recent=await supabase.from('match_days').select('match_date,schedule_generated_at').lte('match_date',today).order('match_date',{ascending:false}).limit(1).maybeSingle();if(recent.data?.match_date&&recent.data.schedule_generated_at){const age=(new Date(today+'T00:00:00')-new Date(recent.data.match_date+'T00:00:00'))/86400000;if(age>=0&&age<=6)return recent.data.match_date;}return nextTuesday();}
export async function loadAll(){if(!state.currentPlayer)return;const player=await refreshCurrentPlayer();if(!player)return;updateAdminVisibility();const date=await currentMatchDayDate();const {data,error}=await supabase.from('match_days').select('id,match_date,poll_open,poll_closed,court_5_cancelled,court_1_cancelled,schedule_generated_at').eq('match_date',date).maybeSingle();if(error){console.error(error);msg($('pollStatus'),error.message);return;}if(!data){$('heroDate').textContent=niceDate(date);$('pollStatus').textContent='Für diesen Dienstag wurde noch kein Spieltag angelegt.';updateAdminVisibility();return;}state.matchDay=data;const m=await loadModules();$('heroDate').textContent=niceDate(data.match_date);await Promise.all([m.poll.loadPoll(),m.schedule.loadAssignments(),m.matches.loadMatches(),m.payments.loadPayments(),m.cancellations.loadCancelledCourts(),m.history.loadHistory(),m.stats.loadStats()]);await m.notifications.loadPushStatus();updateAdminVisibility();}
function updateAdminVisibility(){const adminCard=$('adminCard');const isAdmin=state.currentPlayer?.is_admin===true;document.querySelectorAll('.cancel-court').forEach(b=>{b.style.display=isAdmin?'inline-block':'none';b.setAttribute('aria-hidden',isAdmin?'false':'true');});if(!adminCard)return;if(isAdmin){adminCard.classList.remove('hidden');modules?.admin?.loadPlayerAdmin?.();modules?.admin?.bindAdmin?.();modules?.adminPollTest?.bindAdminPollTest?.();}else adminCard.classList.add('hidden');}
let bindingsReady=false;async function bindFeatureModules(){if(bindingsReady)return;const m=await loadModules();m.poll.bindPoll();m.schedule.bindSchedule();m.admin.bindAdmin();m.notifications.bindPush();m.cancellations.bindCancellations();m.adminPollTest.bindAdminPollTest();document.addEventListener('poll-updated',()=>{if(state.matchDay)m.schedule.loadAssignments().catch(console.error)});bindingsReady=true;}
bindAuth(loadAll);loadLoginPlayers();loadSession(loadAll);bindFeatureModules().catch(e=>console.error('Feature-Module konnten nicht geladen werden:',e));
