import { supabase } from './supabase.js';
import { $, escapeHtml } from './utils.js';

function validSet(a,b){if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b<0||a>7||b>7||a===b)return false;const hi=Math.max(a,b),lo=Math.min(a,b);return(hi===6&&lo<=4)||(hi===7&&(lo===5||lo===6))}
function sets(r){return[[r.set1_home,r.set1_away],[r.set2_home,r.set2_away],[r.set3_home,r.set3_away]].filter(([a,b])=>a!=null&&b!=null&&!(Number(a)===0&&Number(b)===0)).map(([a,b])=>[Number(a),Number(b)]).filter(([a,b])=>validSet(a,b))}
function ensureStyle(){if(document.getElementById('guest-stats-style'))return;const s=document.createElement('style');s.id='guest-stats-style';s.textContent='.guest-stats-box{margin-top:16px}.guest-stat-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto auto;gap:10px;align-items:center;padding:9px 0;border-bottom:1px solid var(--line)}.guest-stat-badge{font-size:10px;padding:2px 7px;border-radius:8px;background:#f1f1f1;font-weight:800}.guest-stat-row:last-child{border-bottom:0}@media(max-width:760px){.guest-stat-row{grid-template-columns:1fr auto auto}.guest-stat-row .guest-sets{grid-column:1/-1;font-size:10px;color:var(--muted)}}';document.head.appendChild(s)}
export async function loadGuestStats(){
 const el=$('statsContent');if(!el)return;ensureStyle();
 const q=await supabase.from('match_days').select('id,assignments(player_id,players:player_id(id,name,is_guest)),match_results(court,set1_home,set1_away,set2_home,set2_away,set3_home,set3_away,team1_player1,team1_player2,team2_player1,team2_player2)').order('match_date',{ascending:true});
 if(q.error)return;
 const guests=new Map();const add=(id,name)=>{id=Number(id);if(!id)return null;if(!guests.has(id))guests.set(id,{id,name:name||'Gast',matches:0,wins:0,losses:0,setsW:0,setsL:0});return guests.get(id)};
 for(const d of q.data||[]){const guestIds=new Set((d.assignments||[]).filter(a=>a.players?.is_guest).map(a=>Number(a.player_id)));if(!guestIds.size)continue;const names=new Map((d.assignments||[]).map(a=>[Number(a.player_id),a.players?.name||'Gast']));for(const r of d.match_results||[]){const ss=sets(r);if(ss.length<2)continue;let aw=0,bw=0;for(const[a,b]of ss){if(a>b)aw++;else bw++}if(Math.max(aw,bw)!==2||aw===bw)continue;const a=[r.team1_player1,r.team1_player2].map(Number).filter(Boolean),b=[r.team2_player1,r.team2_player2].map(Number).filter(Boolean);const winA=aw>bw;for(const id of a.filter(x=>guestIds.has(x))){const g=add(id,names.get(id));g.matches++;g.setsW+=aw;g.setsL+=bw;if(winA)g.wins++;else g.losses++}for(const id of b.filter(x=>guestIds.has(x))){const g=add(id,names.get(id));g.matches++;g.setsW+=bw;g.setsL+=aw;if(!winA)g.wins++;else g.losses++}}}
 const rows=[...guests.values()].filter(g=>g.matches>0).sort((a,b)=>b.wins-a.wins||b.matches-a.matches||a.name.localeCompare(b.name));
 let box=document.getElementById('guest-stats-box');if(!rows.length){if(box)box.remove();return}const html=`<section class="stat-box guest-stats-box" id="guest-stats-box"><h3>👤 Gastspieler</h3><div class="sub">Gastspieler werden separat geführt und nicht in die offizielle Rangliste eingerechnet.</div>${rows.map(g=>`<div class="guest-stat-row"><b>${escapeHtml(g.name)}</b><span class="guest-stat-badge">Gast</span><span>${g.matches} Spiele · ${g.wins} Siege</span><strong>${Math.round(g.wins/g.matches*100)}%</strong><span class="guest-sets">${g.setsW}:${g.setsL} Sätze</span></div>`).join('')}</section>`;if(box)box.outerHTML=html;else el.insertAdjacentHTML('beforeend',html);
}
