import { supabase } from './supabase.js';
import { state } from './state.js';
import { $, msg, escapeHtml } from './utils.js';
import { FUNCTION_URL } from './config.js';

function ensurePreviewBox(){let el=$('schedulePreview');if(el)return el;const courts=document.querySelector('.courts');if(!courts)return null;el=document.createElement('div');el.id='schedulePreview';el.className='schedule-preview';courts.parentNode.insertBefore(el,courts);return el;}
function renderPreview(responses){const el=ensurePreviewBox();if(!el)return;const by={'18:30':[], '19:00':[]};const flex=[];(responses||[]).forEach(r=>{const player=r.players;if(!player)return;const item={player,response:r.response};if(r.response==='18:30')by['18:30'].push(item);else if(r.response==='19:00')by['19:00'].push(item);else if(r.response==='egal')flex.push(item);});
  // Feste Uhrzeiten werden immer exakt dort angezeigt, wo der Spieler abgestimmt hat.
  // Flexible Spieler werden anschließend nur auf noch freie Plätze verteilt.
  while(flex.length&&by['18:30'].length<4)by['18:30'].push(flex.shift());
  while(flex.length&&by['19:00'].length<4)by['19:00'].push(flex.shift());
  const card=(title,time,arr)=>`<div class="preview-court"><div class="preview-head"><div><small>VORLÄUFIG</small><b>${title}</b></div><strong>${time}</strong></div><div class="preview-players">${arr.length?arr.slice(0,4).map(x=>`<span>${escapeHtml(x.player?.name||'Spieler')}${x.player?.is_stammspieler?'<i>Stamm</i>':'<i>Ersatz</i>'}</span>`).join(''):'<span class="preview-empty">Noch keine Zusagen</span>'}</div>${arr.length>4?`<div class="preview-more">+${arr.length-4} weitere Zusage(n) – endgültige Zuordnung folgt</div>`:''}</div>`;
  const overflow=by['18:30'].length+by['19:00'].length>8?`<div class="preview-unassigned">Mehr als 8 Zusagen vorhanden. Die endgültige Einteilung entscheidet, wer tatsächlich spielt.</div>`:'';
  const flexNote=flex.length?`<div class="preview-unassigned">${flex.length} flexible Zusage(n) konnten vorläufig noch keinem freien Platz zugeordnet werden und werden bei der endgültigen Einteilung berücksichtigt.</div>`:'';
  el.innerHTML=`<div class="preview-banner"><div><span class="preview-icon">P</span><div><b>Voraussichtlicher Spielplan</b><p>Feste Uhrzeiten werden genau wie abgestimmt angezeigt. „Egal wann“ wird auf freie Plätze verteilt. Änderungen jederzeit möglich.</p></div></div><strong>Endgültig ab Dienstag 17:00 Uhr</strong></div><div class="preview-grid">${card('Court 5','18:30 Uhr',by['18:30'])}${card('Court 1','19:00 Uhr',by['19:00'])}</div>${overflow}${flexNote}`;el.style.display='block';}
function clearPreview(){const el=$('schedulePreview');if(el)el.style.display='none';}

export async function loadAssignments(){if(!state.matchDay)return;const q=await supabase.from('assignments').select('id,player_id,court,position,manually_changed,players(name,is_stammspieler)').eq('match_day_id',state.matchDay.id).order('court').order('position');if(q.error){msg($('scheduleStatus'),q.error.message);return;}const assignments=q.data||[];const finalGenerated=Boolean(state.matchDay.schedule_generated_at);const render=(arr,el)=>{$(el).innerHTML=arr.length?arr.map(x=>`<div class="player"><b>${escapeHtml(x.players?.name||'Spieler')}</b>${x.players?.is_stammspieler?'<span class="badge">Stammspieler</span>':'<span class="badge">Ersatz</span>'}${x.manually_changed?'<span class="badge">geändert</span>':''}</div>`).join(''):'<div class="player">Noch keine endgültige Zuordnung.</div>';};if(finalGenerated){render(assignments.filter(x=>x.court==='court5'),'court5');render(assignments.filter(x=>x.court==='court1'),'court1');clearPreview();}else{render([], 'court5');render([], 'court1');await loadProvisionalSchedule();}loadMoveControls(finalGenerated?assignments:[]);}
async function loadProvisionalSchedule(){if(!state.matchDay?.id)return;const q=await supabase.from('poll_responses').select('response,players(name,is_stammspieler)').eq('match_day_id',state.matchDay.id);if(q.error){msg($('scheduleStatus'),'Voraussichtlicher Spielplan konnte nicht geladen werden: '+q.error.message);return;}renderPreview(q.data||[]);}
async function refreshPreview(){await loadAssignments();}
document.addEventListener('poll-updated',refreshPreview);
document.addEventListener('schedule-tab-opened',refreshPreview);
async function loadMoveControls(assignments){const playerSelect=$('movePlayer');if(!playerSelect)return;playerSelect.innerHTML='<option value="">Spieler auswählen …</option>'+(assignments.filter(x=>x.player_id).map(x=>`<option value="${x.player_id}">${escapeHtml(x.players?.name||'Spieler')} · ${x.court==='court5'?'Court 5':'Court 1'} · Platz ${x.position}</option>`).join(''));}
async function movePlayer(){if(!state.currentPlayer?.is_admin||!state.matchDay?.id)return;const playerId=Number($('movePlayer')?.value),targetCourt=$('moveCourt')?.value,targetPosition=Number($('movePosition')?.value);if(!playerId||!targetCourt||!targetPosition){msg($('moveStatus'),'Bitte Spieler, Court und Platz auswählen.');return;}const q=await supabase.from('assignments').select('id,player_id,court,position').eq('match_day_id',state.matchDay.id).order('position');if(q.error){msg($('moveStatus'),q.error.message);return;}const rows=q.data||[];const source=rows.find(x=>x.player_id===playerId);if(!source){msg($('moveStatus'),'Spieler ist im aktuellen Spielplan nicht zugeordnet.');return;}if(source.court===targetCourt&&Number(source.position)===targetPosition){msg($('moveStatus'),'Der Spieler steht bereits auf diesem Platz.');return;}const target=rows.find(x=>x.court===targetCourt&&Number(x.position)===targetPosition);if(target&&target.id===source.id)return;if(!confirm(`${source.court==='court5'?'Court 5':'Court 1'} Platz ${source.position} → ${targetCourt==='court5'?'Court 5':'Court 1'} Platz ${targetPosition}${target?.player_id?'\n\nDie beiden Spieler werden getauscht.':''}`))return;if(target?.player_id){const a=await supabase.from('assignments').update({court:targetCourt,position:targetPosition,manually_changed:true}).eq('id',source.id);if(a.error){msg($('moveStatus'),a.error.message);return;}const b=await supabase.from('assignments').update({court:source.court,position:source.position,manually_changed:true}).eq('id',target.id);if(b.error){msg($('moveStatus'),'Der Tausch konnte nicht vollständig gespeichert werden: '+b.error.message);return;}}else{const a=await supabase.from('assignments').update({court:targetCourt,position:targetPosition,manually_changed:true}).eq('id',source.id);if(a.error){msg($('moveStatus'),a.error.message);return;}}msg($('moveStatus'),'Spieler wurde im Spielplan verschoben.',true);await loadAssignments();}
export function bindSchedule(){const button=$('generate');if(button)button.onclick=async()=>{if(!state.currentPlayer?.is_admin){msg($('adminStatus'),'Nur ein Admin kann den Spielplan erzeugen.');return;}if(!state.matchDay?.id){msg($('adminStatus'),'Kein Spieltag geladen.');return;}button.disabled=true;button.textContent='Spielplan wird erzeugt …';msg($('adminStatus'),'Spielplan wird erzeugt …',true);try{const{data:{session},error:sessionError}=await supabase.auth.getSession();if(sessionError)throw new Error('Session konnte nicht geladen werden: '+sessionError.message);if(!session?.access_token)throw new Error('Keine gültige Anmeldung vorhanden.');const res=await fetch(FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({match_day_id:Number(state.matchDay.id)})});let body={};try{body=await res.json();}catch{}if(!res.ok||!body.ok){msg($('adminStatus'),'Spielplan konnte nicht erzeugt werden: '+(body.details||body.error||body.message||('Fehler '+res.status)));return;}const md=await supabase.from('match_days').select('id,match_date,poll_open,poll_closed,court_5_cancelled,court_1_cancelled,schedule_generated_at').eq('id',state.matchDay.id).single();if(md.data)state.matchDay=md.data;await loadAssignments();const summary=(body.assignments||[]).map(x=>`${x.court}: ${x.count} Spieler`).join(' · ');msg($('adminStatus'),'Spielplan wurde erzeugt.'+(summary?' '+summary:''),true);}catch(error){msg($('adminStatus'),error?.message||'Unbekannter Fehler beim Erzeugen des Spielplans.');}finally{button.disabled=false;button.textContent='Spielplan jetzt erzeugen';}};$('movePlayer')?.addEventListener('change',()=>msg($('moveStatus'),'Ziel-Court und Platz auswählen.'));$('movePlayerButton')?.addEventListener('click',movePlayer);}
